import os

SPOTIFY_CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET')

DBUSER = os.getenv('SPOTIFY_RECOMMENDER_DBUSER')
DBPASSWORD = os.getenv('SPOTIFY_RECOMMENDER_DBPASSWORD')
HOST = os.getenv('SPOTIFY_RECOMMENDER_HOST')
DATABASE = os.getenv('SPOTIFY_RECOMMENDER_DATABASE')

DATASET_PATH = "static/spotify_dataset.sql"