import os

SPOTIFY_CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET')

DBUSER = os.getenv('DBUSER')
DBPASSWORD = os.getenv('DBPASSWORD')
HOST = os.getenv('HOST')
DATABASE = os.getenv('DATABASE')